/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visorciutats;

/**
 *
 * @author victormarne
 */
public class teamDetail extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(teamDetail.class.getName());
    
    String equipo;
    String[] TeamHeretics = new String[]{"RieNs","Wo0t","benjyfishy"};
    String[] PaperRex = new String[]{"f0rsakeN","something","Jinggg"};
    String[] FNATIC = new String[]{"Boaster","kaajak","Leo"};
            
    public teamDetail() {
        initComponents();
    }
    public teamDetail (String equipo){
        initComponents();
        this.equipo = equipo;
        this.setTitle(this.equipo + " Players");
        this.lblTeamName.setText(this.equipo);
        this.tglDetailsPlayer.setVisible(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setPlayerNames();
    }
    
    void setPlayerNames(){
        switch (equipo) {
            case "Team Heretics":
                this.radPlayer1.setText(this.TeamHeretics[0]);
                this.radPlayer2.setText(this.TeamHeretics[1]);
                this.radPlayer3.setText(this.TeamHeretics[2]);
                break;
            case "Paper Rex":
                this.radPlayer1.setText(this.PaperRex[0]);
                this.radPlayer2.setText(this.PaperRex[1]);
                this.radPlayer3.setText(this.PaperRex[2]);
                break;
            case "FNATIC":
                this.radPlayer1.setText(this.FNATIC[0]);
                this.radPlayer2.setText(this.FNATIC[1]);
                this.radPlayer3.setText(this.FNATIC[2]);
                break;
            default:
                throw new AssertionError();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPlayers = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        lblTeamName = new javax.swing.JLabel();
        radPlayer1 = new javax.swing.JRadioButton();
        radPlayer2 = new javax.swing.JRadioButton();
        radPlayer3 = new javax.swing.JRadioButton();
        lblPlayerImage = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        tglDetailsPlayer = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Go Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        lblTeamName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTeamName.setText("Team");

        btgPlayers.add(radPlayer1);
        radPlayer1.setText("Player 1");
        radPlayer1.addActionListener(this::radPlayer1ActionPerformed);

        btgPlayers.add(radPlayer2);
        radPlayer2.setText("Player 2");

        btgPlayers.add(radPlayer3);
        radPlayer3.setText("Player 3");

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        tglDetailsPlayer.setText("Toggle Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTeamName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radPlayer1)
                            .addComponent(radPlayer2)
                            .addComponent(radPlayer3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(lblPlayerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tglDetailsPlayer)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTeamName)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radPlayer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radPlayer2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radPlayer3))
                    .addComponent(lblPlayerImage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tglDetailsPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Imagenes i = new Imagenes();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void radPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPlayer1ActionPerformed
        
    }//GEN-LAST:event_radPlayer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new teamDetail().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgPlayers;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblPlayerImage;
    private javax.swing.JLabel lblTeamName;
    private javax.swing.JRadioButton radPlayer1;
    private javax.swing.JRadioButton radPlayer2;
    private javax.swing.JRadioButton radPlayer3;
    private javax.swing.JToggleButton tglDetailsPlayer;
    // End of variables declaration//GEN-END:variables
}
