/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author victormarne
 */
public class Formulario1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario1.class.getName());

    /**
     * Creates new form Formulario1
     */
    public Formulario1() {
        initComponents();
        this.setTitle("Formulario 1");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        btnFormulario2 = new javax.swing.JButton();
        btnIrCalendario = new javax.swing.JButton();
        btnIrImagenes = new javax.swing.JButton();

        jButton2.setText("Ir al Calendario");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFormulario2.setText("Ir al Formulario 2");
        btnFormulario2.addActionListener(this::btnFormulario2ActionPerformed);

        btnIrCalendario.setText("Ir al Calendario");
        btnIrCalendario.addActionListener(this::btnIrCalendarioActionPerformed);

        btnIrImagenes.setText("Ir a Imágenes");
        btnIrImagenes.addActionListener(this::btnIrImagenesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnFormulario2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIrCalendario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnIrImagenes)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnFormulario2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIrImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormulario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormulario2ActionPerformed
        Formulario2 f = new Formulario2("Texto mandado con el constructor");
        f.setVisible(true);
        this.dispose(); // Cierra el formulario actual
        f.lblEtiqueta1.setText("Texto a etiqueta pública");
        f.textoEtiqueta2 = "Texto mandado a un atributo";
    }//GEN-LAST:event_btnFormulario2ActionPerformed

    private void btnIrCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrCalendarioActionPerformed
        Calendario c = new Calendario();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIrCalendarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnIrImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrImagenesActionPerformed
        Imagenes i = new Imagenes();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIrImagenesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormulario2;
    private javax.swing.JButton btnIrCalendario;
    private javax.swing.JButton btnIrImagenes;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
