/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author victormarne
 */
public class Imagenes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Imagenes.class.getName());

    /**
     * Creates new form Imagenes
     */
    public Imagenes() {
        initComponents();
        this.setTitle("Imágenes!!! :)");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgRadios = new javax.swing.ButtonGroup();
        lblImagen = new javax.swing.JLabel();
        radEinstein = new javax.swing.JRadioButton();
        radGato = new javax.swing.JRadioButton();
        mnuMenu = new javax.swing.JMenuBar();
        mnuImagenes = new javax.swing.JMenu();
        mnuEinstein = new javax.swing.JMenuItem();
        mnuGato = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btgRadios.add(radEinstein);
        radEinstein.setText("Einstein");
        radEinstein.addActionListener(this::radEinsteinActionPerformed);

        btgRadios.add(radGato);
        radGato.setText("Gato");
        radGato.addActionListener(this::radGatoActionPerformed);

        mnuImagenes.setText("Imagenes");

        mnuEinstein.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuEinstein.setText("Einstein");
        mnuEinstein.addActionListener(this::mnuEinsteinActionPerformed);
        mnuImagenes.add(mnuEinstein);

        mnuGato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuGato.setText("Gato");
        mnuGato.addActionListener(this::mnuGatoActionPerformed);
        mnuImagenes.add(mnuGato);

        mnuMenu.add(mnuImagenes);

        setJMenuBar(mnuMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radEinstein)
                    .addComponent(radGato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(radEinstein)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radGato)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radEinsteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radEinsteinActionPerformed
        this.mostrarEinstein();
    }//GEN-LAST:event_radEinsteinActionPerformed

    private void radGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radGatoActionPerformed
        this.mostrarGato();
    }//GEN-LAST:event_radGatoActionPerformed

    private void mnuEinsteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEinsteinActionPerformed
        this.mostrarEinstein();
    }//GEN-LAST:event_mnuEinsteinActionPerformed

    private void mnuGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGatoActionPerformed
        this.mostrarGato();
    }//GEN-LAST:event_mnuGatoActionPerformed

    void mostrarEinstein(){
        /*Icon icono = new ImageIcon(this.getClass().getResource("einstein.jpg"));
        this.lblImagen.setIcon(icono);*/
        Image imagen = new ImageIcon(this.getClass().getResource("/imagenes/einstein.jpg")).getImage();
        Image imagenEscalada = imagen.getScaledInstance(this.lblImagen.getWidth(), this.lblImagen.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon iconoEscalado = new ImageIcon(imagenEscalada);
        this.lblImagen.setIcon(iconoEscalado);
        this.radEinstein.setSelected(true);
    }
    void mostrarGato(){
        Image imagen = new ImageIcon(this.getClass().getResource("/imagenes/gato.jpg")).getImage();
        Image imagenEscalada = imagen.getScaledInstance(this.lblImagen.getWidth(), this.lblImagen.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon iconoEscalado = new ImageIcon(imagenEscalada);
        this.lblImagen.setIcon(iconoEscalado);
        this.radGato.setSelected(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Imagenes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgRadios;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JMenuItem mnuEinstein;
    private javax.swing.JMenuItem mnuGato;
    private javax.swing.JMenu mnuImagenes;
    private javax.swing.JMenuBar mnuMenu;
    private javax.swing.JRadioButton radEinstein;
    private javax.swing.JRadioButton radGato;
    // End of variables declaration//GEN-END:variables
}
