/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author victormarne
 */
public class Editar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Editar.class.getName());

    int fila;
    String nombre;
    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
        this.setTitle("Editar registro");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    public Editar(String[] contacto, int fila){
        initComponents();
        this.setTitle("Editar registro");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.fila = fila;
        for (int i = 0; i < contacto.length; i++) {
            String info = contacto[i];
            switch (i) {
                case 0:
                    this.iptNombre.setText(info);
                    this.nombre=info;
                    break;
                case 1:
                    this.iptEmail.setText(info);
                    break;
                case 2:
                    this.iptAp1.setText(info);
                    break;
                case 3:
                    this.iptAp2.setText(info);
                    break;
                case 4:
                    this.iptTelf.setText(info);
                    break;
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblAp1 = new javax.swing.JLabel();
        lblAp2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelf = new javax.swing.JLabel();
        iptTelf = new javax.swing.JTextField();
        iptEmail = new javax.swing.JTextField();
        iptAp2 = new javax.swing.JTextField();
        iptAp1 = new javax.swing.JTextField();
        iptNombre = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Volver");
        btnBack.addActionListener(this::btnBackActionPerformed);

        lblNombre.setText("Nombre");

        lblAp1.setText("Apellido 1");

        lblAp2.setText("Apellido 2");

        lblEmail.setText("Email");

        lblTelf.setText("Telefono");

        iptEmail.addActionListener(this::iptEmailActionPerformed);

        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTelf)
                    .addComponent(lblEmail)
                    .addComponent(lblAp2)
                    .addComponent(lblAp1)
                    .addComponent(lblNombre)
                    .addComponent(btnBack))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iptNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(iptAp1)
                            .addComponent(iptAp2)
                            .addComponent(iptEmail)
                            .addComponent(iptTelf))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                        .addComponent(btnConfirm)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnConfirm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(iptNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAp1)
                    .addComponent(iptAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAp2)
                    .addComponent(iptAp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(iptEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelf)
                    .addComponent(iptTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Todos t = new Todos();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void iptEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptEmailActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        String[] cont = new String[5];
        for (int i = 0; i < cont.length; i++) {
            switch (i) {
                case 0:
                    cont[0]=this.iptNombre.getText();
                    break;
                case 1:
                    cont[1]=this.iptEmail.getText();
                    break;
                case 2:
                    cont[2]=this.iptAp1.getText();
                    break;
                case 3:
                    cont[3]=this.iptAp2.getText();
                    break;
                case 4:
                    cont[4]=this.iptTelf.getText();
                    break;
                default:
                    throw new AssertionError();
            }
        }
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            
            String db="jdbc:ucanaccess:///Users/victormarne/Documents/DAW1/Programacion/POO-Practicas/PrO17-Agenda/Companys.accdb";
            Connection con = DriverManager.getConnection(db);
            
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            int res = s.executeUpdate("UPDATE Dades SET Nom='"+cont[0]+"',Mail='"+cont[1]+"',Cognom1='"+cont[2]+"',Cognom2='"+cont[3]+"',Telefon='"+cont[4]+"' WHERE Nom='"+this.nombre+"' ");
            System.out.println(res + " registros actualizados.");
        } catch (ClassNotFoundException ex) {
            System.out.println("Error al cargar el driver UCanAccess");
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.out.println("Error al concetarse al archivo de Access");
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        Todos t = new Todos();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Editar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JTextField iptAp1;
    private javax.swing.JTextField iptAp2;
    private javax.swing.JTextField iptEmail;
    private javax.swing.JTextField iptNombre;
    private javax.swing.JTextField iptTelf;
    private javax.swing.JLabel lblAp1;
    private javax.swing.JLabel lblAp2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelf;
    // End of variables declaration//GEN-END:variables
}
