/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package agenda;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author victormarne
 */
public class Todos extends javax.swing.JFrame {
    
    ResultSet resultado;
    ResultSet filas;
    String[] contacto = new String[5];

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Todos.class.getName());
    
    /** Creates new form Todos */
    public Todos() {
        initComponents();
        this.setTitle("Todos los registros");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.obtenerFilas();
        this.obtenerTabla();
        try {
            this.imprimirDatos("First");
        } catch (SQLException ex) {
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnBefore = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblAp1 = new javax.swing.JLabel();
        lblAp2 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNFilas = new javax.swing.JLabel();
        lblBarra = new javax.swing.JLabel();
        lblFila = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Volver");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnBefore.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnBefore.setText("◀️");
        btnBefore.setContentAreaFilled(false);
        btnBefore.setFocusPainted(false);
        btnBefore.setFocusable(false);
        btnBefore.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBefore.addActionListener(this::btnBeforeActionPerformed);

        btnLast.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnLast.setText("⏭️");
        btnLast.setContentAreaFilled(false);
        btnLast.setFocusPainted(false);
        btnLast.setFocusable(false);
        btnLast.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLast.addActionListener(this::btnLastActionPerformed);

        btnFirst.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnFirst.setText("️⏮️");
        btnFirst.setContentAreaFilled(false);
        btnFirst.setFocusPainted(false);
        btnFirst.setFocusable(false);
        btnFirst.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnFirst.addActionListener(this::btnFirstActionPerformed);

        btnNext.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnNext.setText("▶️");
        btnNext.setContentAreaFilled(false);
        btnNext.setFocusPainted(false);
        btnNext.setFocusable(false);
        btnNext.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNext.addActionListener(this::btnNextActionPerformed);

        lblNombre.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N

        lblAp1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        lblAp2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        lblBarra.setText("/");

        btnAdd.setText("Añadir");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnEdit.setText("Editar");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setText("Borrar");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblAp1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(83, 83, 83))
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFila)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBarra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNFilas)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnAdd)
                            .addComponent(btnEdit)
                            .addComponent(btnDelete)
                            .addComponent(btnSearch))
                        .addGap(18, 18, 18)
                        .addComponent(lblCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAp1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNFilas)
                            .addComponent(lblBarra)
                            .addComponent(lblFila))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            this.imprimirDatos("Next");
        } catch (SQLException ex) {
            try {
                this.imprimirDatos("Before");
            } catch (SQLException ex1) {
                System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex1);
            }
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try {
            this.imprimirDatos("First");
        } catch (SQLException ex) {
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeforeActionPerformed
        try {
            this.imprimirDatos("Before");
        } catch (SQLException ex) {
            try {
                this.imprimirDatos("Next");
            } catch (SQLException ex1) {
                System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex1);
            }
        }
    }//GEN-LAST:event_btnBeforeActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
            this.imprimirDatos("Last");
        } catch (SQLException ex) {
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Anadir a = new Anadir();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        Busqueda b = new Busqueda();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            Editar e = new Editar(contacto, resultado.getRow());
            e.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        System.out.println("Borrar");
    }//GEN-LAST:event_btnDeleteActionPerformed

    
    void obtenerFilas(){
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            
            String db="jdbc:ucanaccess:///Users/victormarne/Documents/DAW1/Programacion/POO-Practicas/PrO17-Agenda/Companys.accdb";
            Connection con = DriverManager.getConnection(db);
            
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            String sentenciaSQL="select COUNT(*) from Dades";
            filas = s.executeQuery(sentenciaSQL);
            filas.next();
            this.lblNFilas.setText(Integer.toString(filas.getInt(1)));
        } catch (ClassNotFoundException ex) {
            System.out.println("Error al cargar el driver UCanAccess");
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.out.println("Error al concetarse al archivo de Access");
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    void obtenerTabla(){
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            
            String db="jdbc:ucanaccess:///Users/victormarne/Documents/DAW1/Programacion/POO-Practicas/PrO17-Agenda/Companys.accdb";
            Connection con = DriverManager.getConnection(db);
            
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            String sentenciaSQL="select * from Dades ORDER BY Nom";
            resultado = s.executeQuery(sentenciaSQL);
        } catch (ClassNotFoundException ex) {
            System.out.println("Error al cargar el driver UCanAccess");
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.out.println("Error al concetarse al archivo de Access");
            System.getLogger(Todos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    void imprimirDatos(String orden) throws SQLException{
        switch (orden) {
            case "First":
                resultado.first();
                break;
            case "Before":
                resultado.previous();
                break;
            case "Next":
                resultado.next();
                break;
            case "Last":
                resultado.last();
                break;
            default:
                throw new AssertionError();
        }
        this.lblFila.setText(Integer.toString(resultado.getRow()));
        for (int i = 0; i < contacto.length; i++) {
            String columna;
            switch (i) {
                case 0:
                    columna="Nom";
                    break;
                case 1:
                    columna="Mail";
                    break;
                case 2:
                    columna="Cognom1";
                    break;
                case 3:
                    columna="Cognom2";
                    break;
                case 4:
                    columna="Telefon";
                    break;
                default:
                    throw new AssertionError();
            }
            contacto[i]=resultado.getString(columna);
        }
        for (int i = 0; i < contacto.length; i++) {
            switch (i) {
                case 0:
                    this.lblNombre.setText(contacto[i]);
                    break;
                case 1:
                    this.lblCorreo.setText(contacto[i]);
                    break;
                case 2:
                    this.lblAp1.setText(contacto[i]);
                    break;
                case 3:
                    this.lblAp2.setText(contacto[i]);
                    break;
                case 4:
                    this.lblTelefono.setText(contacto[i]);
                    break;
                default:
                    throw new AssertionError();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Todos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBefore;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblAp1;
    private javax.swing.JLabel lblAp2;
    private javax.swing.JLabel lblBarra;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFila;
    private javax.swing.JLabel lblNFilas;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    // End of variables declaration//GEN-END:variables

}
