/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regalos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DAW1
 */
public class Formulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.setTitle("Super Formulario");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtAp1 = new javax.swing.JTextField();
        txtRegalo = new javax.swing.JTextField();
        txtNota = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblAp1 = new javax.swing.JLabel();
        lblRegalo = new javax.swing.JLabel();
        lblNota = new javax.swing.JLabel();
        btnVerDatos = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblNombre.setText("Nombre");

        lblAp1.setText("Apellido");

        lblRegalo.setText("Regalo");

        lblNota.setText("Nota");

        btnVerDatos.setText("Ver Datos");
        btnVerDatos.addActionListener(this::btnVerDatosActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblAp1)
                            .addComponent(lblRegalo)
                            .addComponent(lblNota))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNota, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtRegalo)
                            .addComponent(txtAp1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(btnVerDatos)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAp1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAp1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegalo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegalo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNota))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDatos)
                    .addComponent(btnGuardar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDatosActionPerformed
        this.mostrarDatos();
    }//GEN-LAST:event_btnVerDatosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.guardarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    void mostrarDatos(){
        try {
            // 1. Accedemos al Driver para Access
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            
            // 2. Conectarnos a la Base de Datos Alumnos.accdb
            String db="jdbc:ucanaccess://C:/Users/DAW1/Desktop/tutorial8-base-de-datos/Alumnos.accdb";
            Connection con = DriverManager.getConnection(db);
            
            // 3. Operamos con los registros
            Statement s = con.createStatement();
            String sentenciaSQL="select * from detallitos";
            ResultSet regsFiltrados = s.executeQuery(sentenciaSQL);
            
            // 4. Mostramos los registros filtrados
            System.out.println("Los registros seleccionados son : ");
            while(regsFiltrados.next()==true){
                System.out.println(regsFiltrados.getString("Nombre") + " " + regsFiltrados.getString("Ap1") + 
                        " | Regalo: " + regsFiltrados.getString("Regalo") + " | Nota: " + regsFiltrados.getInt("Nota"));
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("Error al cargar el Driver UCanAccess");
            System.getLogger(Regalos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.out.println("Error al conectarme a la Base de Datos Alumnos.accdb");
            System.getLogger(Regalos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    void guardarDatos(){
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            
            String db="jdbc:ucanaccess://C:/Users/DAW1/Desktop/tutorial8-base-de-datos/Alumnos.accdb";
            Connection con = DriverManager.getConnection(db);
            
            Statement s = con.createStatement();
            String sentenciaSQL="insert into detallitos (nombre,ap1,regalo,nota) values ('"+this.txtNombre.getText()+"','"+this.txtAp1.getText()+"','"+this.txtRegalo.getText()+"',"+this.txtNota.getText()+")";
            int res = s.executeUpdate(sentenciaSQL);
            System.out.println("Registros actualizados = " + res);
            
            
            JOptionPane.showMessageDialog(rootPane, "Registro actualizados =" + res, "¡¡¡Aviso!!!", JOptionPane.INFORMATION_MESSAGE);
            int respuesta = JOptionPane.showOptionDialog(rootPane, "¿Te ha gustado el Tutorial?", "Preguntaaa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(respuesta==JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(rootPane, "¡Qué bien! Me alegro mucho");
            }else{
                JOptionPane.showMessageDialog(rootPane, "¡¡¡Suspendido!!!");
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("Error al cargar el Driver");
            System.getLogger(Formulario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.out.println("Error al conectarnos a la Base de Datos Access.accdb");
            System.getLogger(Formulario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerDatos;
    private javax.swing.JLabel lblAp1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblRegalo;
    private javax.swing.JTextField txtAp1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtRegalo;
    // End of variables declaration//GEN-END:variables
}
