/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen;

import java.awt.Font;

/**
 *
 * @author DAW1
 */
public class Donaciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Donaciones.class.getName());

    /**
     * Creates new form Donaciones
     */
    public Donaciones() {
        initComponents();
        this.setTitle("Donaciones");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.lblMensaje.setText("No hay regalo previo");
    }
    public Donaciones(String regalo){
        initComponents();
        this.setTitle("Donaciones");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        if(regalo.equals("")){
            this.lblMensaje.setText("No hay regalo seleccionado");
        }else{
            this.lblMensaje.setText("El regalo es : " + regalo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgOpcionesRad = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        btgOpcionesBar = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnRegalos = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        rbtMucho = new javax.swing.JRadioButton();
        rbtRegular = new javax.swing.JRadioButton();
        rbtPoco = new javax.swing.JRadioButton();
        rbtNada = new javax.swing.JRadioButton();
        jToolBar1 = new javax.swing.JToolBar();
        tglMucho = new javax.swing.JToggleButton();
        tglRegular = new javax.swing.JToggleButton();
        tglPoco = new javax.swing.JToggleButton();
        tglNada = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mniMucho = new javax.swing.JMenuItem();
        mniRegular = new javax.swing.JMenuItem();
        mniPoco = new javax.swing.JMenuItem();
        mniNada = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Donaciones");

        jButton1.setText("Volver a Principal");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnRegalos.setText("Ir a Regalos");
        btnRegalos.addActionListener(this::btnRegalosActionPerformed);

        btgOpcionesRad.add(rbtMucho);
        rbtMucho.setText("Mucho");
        rbtMucho.addActionListener(this::rbtMuchoActionPerformed);

        btgOpcionesRad.add(rbtRegular);
        rbtRegular.setText("Regular");
        rbtRegular.addActionListener(this::rbtRegularActionPerformed);

        btgOpcionesRad.add(rbtPoco);
        rbtPoco.setText("Poco");
        rbtPoco.addActionListener(this::rbtPocoActionPerformed);

        btgOpcionesRad.add(rbtNada);
        rbtNada.setText("Nada");
        rbtNada.addActionListener(this::rbtNadaActionPerformed);

        jToolBar1.setRollover(true);

        btgOpcionesBar.add(tglMucho);
        tglMucho.setText("Mucho");
        tglMucho.setFocusable(false);
        tglMucho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglMucho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglMucho.addActionListener(this::tglMuchoActionPerformed);
        jToolBar1.add(tglMucho);

        btgOpcionesBar.add(tglRegular);
        tglRegular.setText("Regular");
        tglRegular.setFocusable(false);
        tglRegular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglRegular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglRegular.addActionListener(this::tglRegularActionPerformed);
        jToolBar1.add(tglRegular);

        btgOpcionesBar.add(tglPoco);
        tglPoco.setText("Poco");
        tglPoco.setFocusable(false);
        tglPoco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglPoco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglPoco.addActionListener(this::tglPocoActionPerformed);
        jToolBar1.add(tglPoco);

        btgOpcionesBar.add(tglNada);
        tglNada.setText("Nada");
        tglNada.setFocusable(false);
        tglNada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglNada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglNada.addActionListener(this::tglNadaActionPerformed);
        jToolBar1.add(tglNada);

        jMenu3.setText("Opciones");

        mniMucho.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniMucho.setText("Mucho");
        mniMucho.addActionListener(this::mniMuchoActionPerformed);
        jMenu3.add(mniMucho);

        mniRegular.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniRegular.setText("Regular");
        mniRegular.addActionListener(this::mniRegularActionPerformed);
        jMenu3.add(mniRegular);

        mniPoco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniPoco.setText("Poco");
        mniPoco.addActionListener(this::mniPocoActionPerformed);
        jMenu3.add(mniPoco);

        mniNada.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNada.setText("Nada");
        mniNada.addActionListener(this::mniNadaActionPerformed);
        jMenu3.add(mniNada);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegalos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtMucho)
                            .addComponent(rbtRegular)
                            .addComponent(rbtPoco)
                            .addComponent(rbtNada)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtMucho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtRegular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtPoco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtNada)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnRegalos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegalosActionPerformed
        Regalos r = new Regalos();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegalosActionPerformed

    private void mniMuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMuchoActionPerformed
        this.selectMucho();
    }//GEN-LAST:event_mniMuchoActionPerformed

    private void tglMuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglMuchoActionPerformed
        this.selectMucho();
    }//GEN-LAST:event_tglMuchoActionPerformed

    private void rbtMuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMuchoActionPerformed
        this.selectMucho();
    }//GEN-LAST:event_rbtMuchoActionPerformed

    private void rbtRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRegularActionPerformed
        this.selectRegular();
    }//GEN-LAST:event_rbtRegularActionPerformed

    private void rbtPocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPocoActionPerformed
        this.selectPoco();
    }//GEN-LAST:event_rbtPocoActionPerformed

    private void rbtNadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNadaActionPerformed
        this.selectNada();
    }//GEN-LAST:event_rbtNadaActionPerformed

    private void tglRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglRegularActionPerformed
        this.selectRegular();
    }//GEN-LAST:event_tglRegularActionPerformed

    private void tglPocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglPocoActionPerformed
        this.selectPoco();
    }//GEN-LAST:event_tglPocoActionPerformed

    private void tglNadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglNadaActionPerformed
        this.selectNada();
    }//GEN-LAST:event_tglNadaActionPerformed

    private void mniRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegularActionPerformed
        this.selectRegular();
    }//GEN-LAST:event_mniRegularActionPerformed

    private void mniPocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPocoActionPerformed
        this.selectPoco();
    }//GEN-LAST:event_mniPocoActionPerformed

    private void mniNadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNadaActionPerformed
        this.selectNada();
    }//GEN-LAST:event_mniNadaActionPerformed

    void selectMucho(){
        this.rbtMucho.setSelected(true);
        this.tglMucho.setSelected(true);
        this.mniMucho.setSelected(true);
        this.setLblText(this.txtCantidad.getText(), 10);
    }
    void selectRegular(){
        this.rbtRegular.setSelected(true);
        this.tglRegular.setSelected(true);
        this.mniRegular.setSelected(true);
        this.setLblText(this.txtCantidad.getText(), 5);
    }
    void selectPoco(){
        this.rbtPoco.setSelected(true);
        this.tglPoco.setSelected(true);
        this.mniPoco.setSelected(true);
        this.setLblText(this.txtCantidad.getText(), 2);
    }
    void selectNada(){
        this.rbtNada.setSelected(true);
        this.tglNada.setSelected(true);
        this.mniNada.setSelected(true);
        this.setLblText();
    }
    void setLblText(){
        this.txtCantidad.setText("Creo que nos veremos en septiembre. :-(");
    }
    void setLblText(String txt, int mult){
        this.txtCantidad.setText(txt+"*"+mult);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Donaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgOpcionesBar;
    private javax.swing.ButtonGroup btgOpcionesRad;
    private javax.swing.JButton btnRegalos;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem mniMucho;
    private javax.swing.JMenuItem mniNada;
    private javax.swing.JMenuItem mniPoco;
    private javax.swing.JMenuItem mniRegular;
    private javax.swing.JRadioButton rbtMucho;
    private javax.swing.JRadioButton rbtNada;
    private javax.swing.JRadioButton rbtPoco;
    private javax.swing.JRadioButton rbtRegular;
    private javax.swing.JToggleButton tglMucho;
    private javax.swing.JToggleButton tglNada;
    private javax.swing.JToggleButton tglPoco;
    private javax.swing.JToggleButton tglRegular;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
