/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author DAW1
 */
public class Regalos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Regalos.class.getName());

    /**
     * Creates new form Regalos
     */
    public Regalos() {
        initComponents();
        this.setTitle("Regalos Juan :-)");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnDonaciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRegalos = new javax.swing.JList<>();
        lblTitulo = new javax.swing.JLabel();
        lblFotoRegalo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Volver a Principal");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnDonaciones.setText("Ir a Donaciones");
        btnDonaciones.addActionListener(this::btnDonacionesActionPerformed);

        lstRegalos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Jamon", "Bombones", "Gominolas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstRegalos.addPropertyChangeListener(this::lstRegalosPropertyChange);
        lstRegalos.addListSelectionListener(this::lstRegalosValueChanged);
        jScrollPane1.setViewportView(lstRegalos);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Regalos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDonaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(lblFotoRegalo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFotoRegalo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDonaciones)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDonacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonacionesActionPerformed
        Donaciones d;
        if(this.lstRegalos.getSelectedIndex()>=0){
            d = new Donaciones(this.lstRegalos.getSelectedValue());
        }else{
            d = new Donaciones();
        }
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDonacionesActionPerformed

    private void lstRegalosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lstRegalosPropertyChange
        
    }//GEN-LAST:event_lstRegalosPropertyChange

    private void lstRegalosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRegalosValueChanged
        ImageIcon imagen = new ImageIcon();
        switch (this.lstRegalos.getSelectedIndex()) {
            case 0:
                imagen = new ImageIcon(getClass().getResource("/imagenes/jamon.jpg"));
                break;
            case 1:
                imagen = new ImageIcon(getClass().getResource("/imagenes/bombones.jpg"));
                break;
            case 2:
                imagen = new ImageIcon(getClass().getResource("/imagenes/gominolas.jpg"));
                break;
        }
        ImageIcon imagenE = new ImageIcon(imagen.getImage().getScaledInstance(this.lblFotoRegalo.getWidth(), this.lblFotoRegalo.getHeight(), 0));
        this.lblFotoRegalo.setIcon(imagenE);
    }//GEN-LAST:event_lstRegalosValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Regalos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDonaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFotoRegalo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstRegalos;
    // End of variables declaration//GEN-END:variables
}
