package editor;

import java.awt.Color;
import java.awt.Font;

public class Formulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());

    public Formulario() {
        initComponents();
        this.setTitle("Super editor de textos!!!");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.cboColorFondo.setSelectedIndex(-1); // Al empezar no hay nada seleccionado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgColorLetra = new javax.swing.ButtonGroup();
        txtTexto = new javax.swing.JTextField();
        chkNegrita = new javax.swing.JCheckBox();
        chkCursiva = new javax.swing.JCheckBox();
        cboColorFondo = new javax.swing.JComboBox<>();
        radVerde = new javax.swing.JRadioButton();
        radNegro = new javax.swing.JRadioButton();
        radCyan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTamaño = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkNegrita.setText("Negrita");
        chkNegrita.addActionListener(this::chkNegritaActionPerformed);

        chkCursiva.setText("Cursiva");
        chkCursiva.addActionListener(this::chkCursivaActionPerformed);

        cboColorFondo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Amarillo", "Azul" }));
        cboColorFondo.addActionListener(this::cboColorFondoActionPerformed);

        btgColorLetra.add(radVerde);
        radVerde.setText("Verde");
        radVerde.addActionListener(this::radVerdeActionPerformed);

        btgColorLetra.add(radNegro);
        radNegro.setText("Negro");
        radNegro.addActionListener(this::radNegroActionPerformed);

        btgColorLetra.add(radCyan);
        radCyan.setText("Cyan");
        radCyan.addActionListener(this::radCyanActionPerformed);

        lstTamaño.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "10", "20", "30", "40" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstTamaño.addListSelectionListener(this::lstTamañoValueChanged);
        jScrollPane1.setViewportView(lstTamaño);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTexto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkNegrita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(cboColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(radVerde))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(chkCursiva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radCyan)
                                    .addComponent(radNegro))))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkNegrita)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCursiva)
                            .addComponent(radNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radCyan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNegritaActionPerformed
        Font fuente = this.txtTexto.getFont();
        int estilo = fuente.getStyle(); // Capturamos el estilo de la fuente del txtTexto
        if(this.chkNegrita.isSelected()==true){
            estilo = estilo + Font.BOLD;
        }else{
            estilo = estilo - Font.BOLD;
        }
        // Actualizamos la fuente del txtTexto otra vez
        fuente = fuente.deriveFont(estilo);
        this.txtTexto.setFont(fuente);
    }//GEN-LAST:event_chkNegritaActionPerformed

    private void chkCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCursivaActionPerformed
        Font fuente = this.txtTexto.getFont();
        int estilo = fuente.getStyle();
        if(this.chkCursiva.isSelected()==true){
            estilo = estilo + Font.ITALIC;
        }else{
            estilo = estilo - Font.ITALIC;
        }
        fuente = fuente.deriveFont(estilo);
        this.txtTexto.setFont(fuente);
    }//GEN-LAST:event_chkCursivaActionPerformed

    private void cboColorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboColorFondoActionPerformed
        switch(this.cboColorFondo.getSelectedIndex()){
            case 0: // Rojo
                this.txtTexto.setBackground(Color.red);
                break;
            case 1: // Amarillo
                this.txtTexto.setBackground(Color.yellow);
                break;
            case 2: // Azul
                this.txtTexto.setBackground(Color.blue);
                break;
        }
    }//GEN-LAST:event_cboColorFondoActionPerformed

    private void radNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNegroActionPerformed
        this.txtTexto.setForeground(Color.black);
    }//GEN-LAST:event_radNegroActionPerformed

    private void radCyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCyanActionPerformed
        this.txtTexto.setForeground(Color.cyan);
    }//GEN-LAST:event_radCyanActionPerformed

    private void radVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radVerdeActionPerformed
        this.txtTexto.setForeground(Color.green);
    }//GEN-LAST:event_radVerdeActionPerformed

    private void lstTamañoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTamañoValueChanged
        Font fuente = this.txtTexto.getFont();
        float tamano = fuente.getSize();
        switch(this.lstTamaño.getSelectedIndex()){
            case 0: // tamaño 10
                tamano=10;
                break;
            case 1: // tamaño 20
                tamano=20;
                break;
            case 2: // tamaño 30
                tamano=30;
                break;
            case 3: // tamaño 40
                tamano=40;
                break;
        }
        fuente = fuente.deriveFont(tamano);
        this.txtTexto.setFont(fuente);
    }//GEN-LAST:event_lstTamañoValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgColorLetra;
    private javax.swing.JComboBox<String> cboColorFondo;
    private javax.swing.JCheckBox chkCursiva;
    private javax.swing.JCheckBox chkNegrita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstTamaño;
    private javax.swing.JRadioButton radCyan;
    private javax.swing.JRadioButton radNegro;
    private javax.swing.JRadioButton radVerde;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
